name: Drupal Composer

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: composer downgrade to 2.2
      run: sudo composer self-update --2.2
      
    - name: Validate composer.json and composer.lock
      run: composer validate

   # - name: Cache Composer packages
   #   id: composer-cache
   #   uses: actions/cache@v3
    #  with:
   #     path: vendor
   #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #    restore-keys: |
    #      ${{ runner.os }}-php-
          
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with: 
        php-version: '7.4.33'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --no-suggest --no-interaction

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with: 
        host: ${{vars.STALLIONI_HOST}}
        username: ${{vars.STALLIONI_USERNAME}}
        password: ${{secrets.STALLIONI_PASS}}
        script: |
          cd /var/www/clients/client0/web16/web/
          sudo git config --global --add safe.directory /var/www/clients/client0/web16/web
          sudo git pull origin master
          sudo chown -R $USER:$USER /var/www/clients/client0/web16/web
          sudo chmod -R 775 /var/www/clients/client0/web16/web
          pwd
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader --no-interaction
          pwd
    #      vendor/bin/drush cr
    #      vendor/bin/drush updb -y
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
