name: Drupal Composer

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Setup PHP
      uses: shivammathur@setup-php@v2
      with: 
        php-version: ">=7.4.33"

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with: 
        host: ${{secrets.AZURE_SSH_HOST}}
        username: ${{secrets.AZURE_USERNAME}}
        key: ${{secrets.AZURE_PUBLIC_KEY}}
        script: |
          cd /var/www/html/
          git pull origin master
          composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
          drush cr
          drush updb -y
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
